<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>

<!-- BEGIN (write your solution here) -->
<form action='/session' name="Sign In" method='post'>
    <?php if ($currentUser): ?>
        <label><?= $currentUser['name']; ?></label>
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    <?php else: ?>
        <div>
            <label>
                Sign In
            </label>
        </div>    
        <div>
            <label>
                Name:
                <input type="text" require name="user[name]">
            </label>
        </div>    
        <div>
            <label>
                Password
                <input type="password" require name="user[password]">
            </label>
        </div>
        <input type="submit" value="Sign In">
    <?php endif; ?>    
</form>
<!-- END -->
